### ISSUE TITLE
not define model

### ISSUE THREAD

**Issue by yaodehaung** [CalvertYang/node-allpay#4]
我在執行test file 中的 js  有一些裡面載入的寫法都有錯誤

**Comment by CalvertYang** [comment]
我剛測試發現 devDependencies 少了 bunyan，補上後使用 mocha 測試正常。

不曉得你說的 not define model 是那邊有問題？方便的話再麻煩附上截圖，謝謝。

**Comment by yaodehaung** [comment]
@
![Uploading 2016-04-20 15:46:28 的螢幕擷圖.png…]()

**Comment by yaodehaung** [comment]
![Uploading 2016-04-20 15:46:28 的螢幕擷圖.png…](執行allplay_spec.js不行）

**Comment by yaodehaung** [comment]
![2016-04-20 15 46 28](https://cloud.githubusercontent.com/assets/8554998/14667041/9a1dd5ba-070f-11e6-8227-b540abf734a5.png)

**Comment by CalvertYang** [comment]
你執行測試的方式錯了喔！

用以下兩種方法都可以發動測試：

1. 在專案根目錄以相對路徑執行 node_modules 內 mocha
```bash
$ ./node_modules/mocha/bin/mocha
```

2. 在全域安裝 mocha，然後在專案根目錄執行 mocha
```bash
$ npm install mocha -g
$ mocha
```
